# Generated by Django 3.2 on 2021-05-05 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('phone_no', models.CharField(default='(+91) 738 966 6837', max_length=20)),
                ('github_profile', models.CharField(blank=True, default='https://www..com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('github_url', models.CharField(blank=True, default='https://www.github.com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('linkedin_url', models.CharField(blank=True, default='https://www.linkedin.com/in/animesh-sharma-73300a161/', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('kaggle_url', models.CharField(blank=True, default='https://www.kaggle.com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('twitter_url', models.CharField(blank=True, default='https://www.twitter.com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('instagram_url', models.CharField(blank=True, default='https://www.instagram.com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')])),
                ('years_of_experience', models.IntegerField(default=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
