# Generated by Django 3.2 on 2021-05-05 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myself',
            name='github_url',
        ),
        migrations.AlterField(
            model_name='myself',
            name='github_profile',
            field=models.CharField(blank=True, default='https://www.github.com/animesharma3', max_length=300, validators=[django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Invalid URL')]),
        ),
    ]
