# Generated by Django 3.2 on 2021-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0002_auto_20210505_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='myself',
            name='address',
            field=models.TextField(default='62, Karamchari Colony, Station Road, Dewas'),
        ),
        migrations.AddField(
            model_name='myself',
            name='profile_header',
            field=models.TextField(default='Data Scientist | Machine Learning Engineer | Full Stack Web Developer'),
        ),
    ]
