# Generated by Django 3.2 on 2021-05-10 09:36

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
